name: Update mma data
on:
  schedule:
    - cron: 0 9,19 * * *
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: py-actions/py-dependency-install@v4
        with:
          path: requirements.txt
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          API_KEY: ${{ secrets.API_KEY }}
      - run: |
          git pull
          python fetch.py
          git config --global user.email "trulybright@yonsei.ac.kr"
          git config --global user.name "TrulyBright"
          git add -A
          git commit -m "update data"
          git push
      - uses: Azure/static-web-apps-deploy@v1
        env:
          PRE_BUILD_COMMAND: npm install -g pnpm
          CUSTOM_BUILD_COMMAND: pnpm install && pnpm run build
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_RIVER_005A91700 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/front" # App source code path
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
