name: Update mma data
on:
  schedule:
  - cron: 0 * * * *
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      - name: Update data.json
        run: |
          python updater.py
          git add -A
          git commit -m "update data.json"
          git push
