name: Update
on:
    schedule:
        - cron: 0 * * * *
jobs:
    Deploy-to-the-Azure-SWA:
        runs-on: ubuntu-latest
        env:
            API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
            API_KEY: ${{ secrets.API_KEY }}
            GITHUB_TOKEN: ${{ secrets.GIST_ACCESS_TOKEN }}
            GIST_ID: ${{ secrets.GIST_ID }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                python fetch.py
            - uses: Azure/static-web-apps-deploy@v1
              env:
                PRE_BUILD_COMMAND: npm i -g pnpm
                CUSTOM_BUILD_COMMAND: pnpm i && pnpm run build-with-data
              with:
                azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_RIVER_005A91700 }}
                repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                action: "upload"
                app_location: "/front" # App source code path
                output_location: "dist" #  Built app content directory, relative to app_location - optional